version: "3.8"

services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: shalom_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shalom_dhis2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: shalom_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: password
      DB_NAME: shalom_dhis2
    ports:
      - "3001:3000"
    depends_on:
      - postgres

  frontend_web:
    build: ./frontend_web
    container_name: shalom_web
    ports:
      - "5173:5173"
    depends_on:
      - backend

  frontend_mobile:
    build: ./frontend_mobile
    container_name: shalom_mobile
    ports:
      - "19000:19000"
    depends_on:
      - backend

volumes:
  pgdata:
